server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /views/
      suffix: .html
        
  datasource:
#    name: studyroom
    url: jdbc:mysql://localhost:3306/studyroom?
    username: root
    password: 802117
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      schema-locations: classpath:mySchema.sql
      data-locations: classpath:myData.sql
      mode: always

mybatis:
  mapper-locations: classpath:com.huawei.ibooking.mapper/*.xml
  type-aliases-package: com.huawei.ibooking.model

logging:
  level:
    com.huawei.ibooking: debug
